server:
  port: 8080

# Example route config (to be updated as you add services)
spring:
  application:
    name: api-gateway
  # cloud is the namespace for the gateway

  profiles:
    include: shared
  
  config:
    import: file:../shared-config/application.yml

  cloud:
    # gateway is the namespace for the gateway
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**
            - id: url-service
              uri: lb://url-service
              predicates:
                - Path=/api/urls/**, /[a-zA-Z0-9]+
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT Configuration (fallback)
jwt:
  secret: "${JWT_SECRET:jwt-secret-fallback}"
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: "url-shortner-application"


