spring:
  application:
    name: url-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/urldb}
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          use_sql_comments: true
          type: trace

#  h2:
#    console:
#      enabled: true
#      path: /h2-console


  
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
